send_personal:
  name: Send Personal Message
  description: Kirim pesan WhatsApp ke nomor personal.
  fields:
    sender:
      name: Session Name
      description: Session name WAHA yang akan digunakan.
      required: true
      example: "device_1"
      selector:
        text:
    phone:
      name: Phone
      description: Nomor tujuan.
      required: true
      example: "6289876543210"
      selector:
        text:
    message:
      name: Message
      description: Isi pesan.
      required: true
      example: "Pintu depan terbuka!"
      selector:
        text:

send_group:
  name: Send Group Message
  description: Kirim pesan WhatsApp ke grup.
  fields:
    sender:
      name: Session Name
      description: Session name WAHA yang akan digunakan.
      required: true
      example: "device_1"
      selector:
        text:
    group_id:
      name: Group ID
      description: ID grup tujuan.
      required: true
      example: "1203630xxxxxxxx"
      selector:
        text:
    message:
      name: Message
      description: Isi pesan.
      required: true
      example: "Backup server selesai."
      selector:
        text:

check_phone:
  name: Check Phone
  description: Cek apakah nomor tersedia di WhatsApp.
  fields:
    sender:
      name: Session Name
      description: Session name WAHA yang akan digunakan.
      required: true
      example: "device_1"
      selector:
        text:
    phone:
      name: Phone
      description: Nomor yang ingin dicek.
      required: true
      example: "6289876543210"
      selector:
        text:
